import { useState } from 'react';
import {
  useEvidencePacks,
  useGenerateEvidencePack,
  type EvidencePackFilters,
} from '../../hooks/useEvidencePack';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from '@/components/ui/table';

const statusVariant: Record<string, 'default' | 'secondary' | 'destructive'> = {
  GENERATING: 'secondary',
  READY: 'default',
  FAILED: 'destructive',
};

export function EvidencePack() {
  const [filters, setFilters] = useState<EvidencePackFilters>({
    page: 1,
    limit: 20,
  });
  const { data, isLoading, error, refetch } = useEvidencePacks(filters);
  const generatePack = useGenerateEvidencePack();

  const [showForm, setShowForm] = useState(false);
  const [formName, setFormName] = useState('');
  const [formFrom, setFormFrom] = useState('');
  const [formTo, setFormTo] = useState('');

  const handleGenerate = () => {
    if (!formName || !formFrom || !formTo) return;
    generatePack.mutate(
      { name: formName, fromDate: formFrom, toDate: formTo },
      {
        onSuccess: () => {
          setShowForm(false);
          setFormName('');
          setFormFrom('');
          setFormTo('');
          void refetch();
        },
      },
    );
  };

  return (
    <div className="p-6">
      <div className="flex justify-between items-center mb-6">
        <h2 className="m-0 text-xl font-bold">Evidence Packs</h2>
        <Button
          onClick={() => setShowForm(!showForm)}
        >
          {showForm ? 'Cancel' : 'Generate New Pack'}
        </Button>
      </div>

      {/* Generation form */}
      {showForm && (
        <div className="p-4 bg-slate-50 rounded-lg border border-slate-200 mb-6 flex gap-4 flex-wrap items-end">
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium text-slate-600">
              Pack Name
            </label>
            <Input
              type="text"
              value={formName}
              onChange={(e) => setFormName(e.target.value)}
              placeholder="Q1 2026 Compliance"
              className="min-w-[140px]"
            />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium text-slate-600">
              From Date
            </label>
            <Input
              type="date"
              value={formFrom}
              onChange={(e) => setFormFrom(e.target.value)}
              className="min-w-[140px]"
            />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs font-medium text-slate-600">
              To Date
            </label>
            <Input
              type="date"
              value={formTo}
              onChange={(e) => setFormTo(e.target.value)}
              className="min-w-[140px]"
            />
          </div>
          <Button
            onClick={handleGenerate}
            disabled={generatePack.isPending || !formName || !formFrom || !formTo}
            className="bg-emerald-500 hover:bg-emerald-600"
          >
            {generatePack.isPending ? 'Generating...' : 'Generate'}
          </Button>
        </div>
      )}

      {isLoading && <p>Loading evidence packs...</p>}
      {error && (
        <p className="text-red-600">
          Error: {error instanceof Error ? error.message : 'Unknown error'}
        </p>
      )}

      {data && (
        <>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead className="whitespace-nowrap">Name</TableHead>
                <TableHead className="whitespace-nowrap">Status</TableHead>
                <TableHead className="whitespace-nowrap">Period</TableHead>
                <TableHead className="whitespace-nowrap">Log Count</TableHead>
                <TableHead className="whitespace-nowrap">Generated By</TableHead>
                <TableHead className="whitespace-nowrap">Created</TableHead>
                <TableHead className="whitespace-nowrap">Download</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {data.data.map((pack) => (
                <TableRow key={pack.id}>
                  <TableCell className="font-medium">{pack.name}</TableCell>
                  <TableCell>
                    <Badge
                      variant={statusVariant[pack.status] ?? 'secondary'}
                    >
                      {pack.status}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    {new Date(pack.fromDate).toLocaleDateString()} -{' '}
                    {new Date(pack.toDate).toLocaleDateString()}
                  </TableCell>
                  <TableCell>{pack.auditLogCount}</TableCell>
                  <TableCell>{pack.generatedBy}</TableCell>
                  <TableCell>
                    {new Date(pack.createdAt).toLocaleString()}
                  </TableCell>
                  <TableCell>
                    {pack.downloadUrl ? (
                      <a
                        href={pack.downloadUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-600 underline"
                      >
                        Download
                      </a>
                    ) : (
                      <span className="text-slate-400">-</span>
                    )}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          <div className="flex gap-2 mt-4">
            <Button
              variant="outline"
              size="sm"
              disabled={filters.page === 1}
              onClick={() =>
                setFilters((prev) => ({ ...prev, page: (prev.page ?? 1) - 1 }))
              }
            >
              Previous
            </Button>
            <Button
              variant="outline"
              size="sm"
              disabled={data.data.length < (filters.limit ?? 20)}
              onClick={() =>
                setFilters((prev) => ({ ...prev, page: (prev.page ?? 1) + 1 }))
              }
            >
              Next
            </Button>
          </div>
        </>
      )}
    </div>
  );
}

export default EvidencePack;
