import { useState } from 'react';
import {
  useEvidencePacks,
  useGenerateEvidencePack,
  type EvidencePackFilters,
} from '../../hooks/useEvidencePack';

const statusColor: Record<string, string> = {
  GENERATING: '#f59e0b',
  READY: '#10b981',
  FAILED: '#ef4444',
};

export function EvidencePack() {
  const [filters, setFilters] = useState<EvidencePackFilters>({
    page: 1,
    limit: 20,
  });
  const { data, isLoading, error, refetch } = useEvidencePacks(filters);
  const generatePack = useGenerateEvidencePack();

  const [showForm, setShowForm] = useState(false);
  const [formName, setFormName] = useState('');
  const [formFrom, setFormFrom] = useState('');
  const [formTo, setFormTo] = useState('');

  const handleGenerate = () => {
    if (!formName || !formFrom || !formTo) return;
    generatePack.mutate(
      { name: formName, fromDate: formFrom, toDate: formTo },
      {
        onSuccess: () => {
          setShowForm(false);
          setFormName('');
          setFormFrom('');
          setFormTo('');
          void refetch();
        },
      },
    );
  };

  return (
    <div style={{ padding: '1.5rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
        <h2 style={{ margin: 0 }}>Evidence Packs</h2>
        <button
          onClick={() => setShowForm(!showForm)}
          style={{
            padding: '0.5rem 1rem',
            backgroundColor: '#2563eb',
            color: '#fff',
            border: 'none',
            borderRadius: '4px',
            cursor: 'pointer',
            fontWeight: 600,
          }}
        >
          {showForm ? 'Cancel' : 'Generate New Pack'}
        </button>
      </div>

      {/* Generation form */}
      {showForm && (
        <div style={{
          padding: '1rem',
          backgroundColor: '#f8fafc',
          borderRadius: '8px',
          border: '1px solid #e2e8f0',
          marginBottom: '1.5rem',
          display: 'flex',
          gap: '1rem',
          flexWrap: 'wrap',
          alignItems: 'flex-end',
        }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
            <label style={{ fontSize: '0.8rem', fontWeight: 500, color: '#475569' }}>
              Pack Name
            </label>
            <input
              type="text"
              value={formName}
              onChange={(e) => setFormName(e.target.value)}
              placeholder="Q1 2026 Compliance"
              style={inputStyle}
            />
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
            <label style={{ fontSize: '0.8rem', fontWeight: 500, color: '#475569' }}>
              From Date
            </label>
            <input
              type="date"
              value={formFrom}
              onChange={(e) => setFormFrom(e.target.value)}
              style={inputStyle}
            />
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
            <label style={{ fontSize: '0.8rem', fontWeight: 500, color: '#475569' }}>
              To Date
            </label>
            <input
              type="date"
              value={formTo}
              onChange={(e) => setFormTo(e.target.value)}
              style={inputStyle}
            />
          </div>
          <button
            onClick={handleGenerate}
            disabled={generatePack.isPending || !formName || !formFrom || !formTo}
            style={{
              padding: '0.5rem 1.5rem',
              backgroundColor: '#10b981',
              color: '#fff',
              border: 'none',
              borderRadius: '4px',
              cursor: 'pointer',
              fontWeight: 600,
            }}
          >
            {generatePack.isPending ? 'Generating...' : 'Generate'}
          </button>
        </div>
      )}

      {isLoading && <p>Loading evidence packs...</p>}
      {error && (
        <p style={{ color: '#dc2626' }}>
          Error: {error instanceof Error ? error.message : 'Unknown error'}
        </p>
      )}

      {data && (
        <>
          <div style={{ overflowX: 'auto' }}>
            <table style={tableStyle}>
              <thead>
                <tr>
                  <th style={thStyle}>Name</th>
                  <th style={thStyle}>Status</th>
                  <th style={thStyle}>Period</th>
                  <th style={thStyle}>Log Count</th>
                  <th style={thStyle}>Generated By</th>
                  <th style={thStyle}>Created</th>
                  <th style={thStyle}>Download</th>
                </tr>
              </thead>
              <tbody>
                {data.data.map((pack) => (
                  <tr key={pack.id}>
                    <td style={{ ...tdStyle, fontWeight: 500 }}>{pack.name}</td>
                    <td style={tdStyle}>
                      <span
                        style={{
                          display: 'inline-block',
                          padding: '0.125rem 0.5rem',
                          borderRadius: '999px',
                          fontSize: '0.75rem',
                          fontWeight: 600,
                          color: '#fff',
                          backgroundColor: statusColor[pack.status] ?? '#94a3b8',
                        }}
                      >
                        {pack.status}
                      </span>
                    </td>
                    <td style={tdStyle}>
                      {new Date(pack.fromDate).toLocaleDateString()} -{' '}
                      {new Date(pack.toDate).toLocaleDateString()}
                    </td>
                    <td style={tdStyle}>{pack.auditLogCount}</td>
                    <td style={tdStyle}>{pack.generatedBy}</td>
                    <td style={tdStyle}>
                      {new Date(pack.createdAt).toLocaleString()}
                    </td>
                    <td style={tdStyle}>
                      {pack.downloadUrl ? (
                        <a
                          href={pack.downloadUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          style={{ color: '#2563eb', textDecoration: 'underline' }}
                        >
                          Download
                        </a>
                      ) : (
                        <span style={{ color: '#94a3b8' }}>-</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div style={{ display: 'flex', gap: '0.5rem', marginTop: '1rem' }}>
            <button
              disabled={filters.page === 1}
              onClick={() =>
                setFilters((prev) => ({ ...prev, page: (prev.page ?? 1) - 1 }))
              }
              style={btnStyle}
            >
              Previous
            </button>
            <button
              disabled={data.data.length < (filters.limit ?? 20)}
              onClick={() =>
                setFilters((prev) => ({ ...prev, page: (prev.page ?? 1) + 1 }))
              }
              style={btnStyle}
            >
              Next
            </button>
          </div>
        </>
      )}
    </div>
  );
}

export default EvidencePack;

const inputStyle: React.CSSProperties = {
  padding: '0.5rem 0.75rem',
  border: '1px solid #ddd',
  borderRadius: '4px',
  fontSize: '0.875rem',
  minWidth: '140px',
};

const tableStyle: React.CSSProperties = {
  width: '100%',
  borderCollapse: 'collapse',
  fontSize: '0.875rem',
};

const thStyle: React.CSSProperties = {
  textAlign: 'left',
  padding: '0.625rem 0.75rem',
  borderBottom: '2px solid #e2e8f0',
  fontWeight: 600,
  color: '#475569',
  whiteSpace: 'nowrap',
};

const tdStyle: React.CSSProperties = {
  padding: '0.5rem 0.75rem',
  borderBottom: '1px solid #f1f5f9',
  color: '#334155',
};

const btnStyle: React.CSSProperties = {
  padding: '0.5rem 1rem',
  border: '1px solid #ddd',
  borderRadius: '4px',
  backgroundColor: '#fff',
  cursor: 'pointer',
  fontSize: '0.85rem',
};
